### ISSUE TITLE
No such export SendAlert in resource mythic_notify.

### ISSUE THREAD

**Issue by Achim-Sommer** [utkuali/Fleeca-Bank-Heists#1]
SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:924: No such export SendAlert in resource mythic_notify.

I have mythic_notify in my resources folder.

**Comment by utkuali** [comment]
Change every SendAlert to DoHudText in utk_fleeca/client.lua

**Comment by Achim-Sommer** [comment]
Is not necessary, i fixt it. 
My mythic_notiy Version was 1.0.3 now with 1.1.0 it works. Thanks for the answer anyway :)
