### ISSUE TITLE
only able to loot one table of cash

### ISSUE THREAD

**Issue by rahafuf** [utkuali/Fleeca-Bank-Heists#2]
for some reason when you loot any table of cash it stops the rest of the script. how can I fix this?

**Comment by utkuali** [comment]
it does not stop, you ran out of time, it is meant that way to force players to rob the bank as a team not alone

**Comment by rahafuf** [comment]
Well it was. I looted one table. Still had like 30 secs and couldn't loot
others and couldn't use the key card either.
